name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: configure
      run: brew install llvm cmake
    - uses: actions/checkout@v3
    - name: make dirs
      run: mkdir build && cd build
    - name: cmake configuring
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
