name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Update brew
      run: brew upgrade
    - name: configure
      run: brew install llvm dmd cmake rust zstd gcc zig
    - name: install pexpect
      run: pip3 install pexpect
    - uses: actions/checkout@v3
    - name: cmake configuring
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DFISH_USE_SYSTEM_PCRE2=OFF -DWITH_GETTEXT=NO -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"
    - name: cmake build
      run: cmake --build build
